const states = {
  "nsw": [
    "Aberdare",
    "Albury",
    "Alstonville",
    "Anna Bay",
    "Appin",
    "Armidale",
    "Ballina",
    "Banora Point",
    "Bargo",
    "Batemans Bay",
    "Bathurst",
    "Bay View",
    "Bega",
    "Bellingen",
    "Berry",
    "Blackheath",
    "Blaxland",
    "Blayney",
    "Bogangar",
    "Bomaderry",
    "Bonny Hills",
    "Bonville",
    "Bowral",
    "Broken Hill",
    "Bundanoon",
    "Bungendore",
    "Burradoo",
    "Byron Bay",
    "Camden",
    "Campbelltown",
    "Casino",
    "Central Coast",
    "Cessnock",
    "Cobar",
    "Coffs Harbour",
    "Condobolin",
    "Cooma",
    "Coonabarabran",
    "Coonamble",
    "Cooranbong",
    "Cootamundra",
    "Corowa",
    "Cowra",
    "Crookwell",
    "Culburra",
    "Deniliquin",
    "Dubbo",
    "East Ballina",
    "East Hills",
    "Eden",
    "Emu Plains",
    "Evans Head",
    "Faulconbridge",
    "Finley",
    "Forbes",
    "Forster",
    "Gerringong",
    "Gilgandra",
    "Glen Innes",
    "Glenbrook",
    "Gloucester",
    "Goonellabah",
    "Gosford",
    "Goulburn",
    "Grafton",
    "Grenfell",
    "Greta",
    "Griffith",
    "Gulgong",
    "Gunnedah",
    "Hazelbrook",
    "Helensburgh",
    "Hill Top",
    "Howlong",
    "Inverell",
    "Jindabyne",
    "Junee",
    "Katoomba",
    "Kelso",
    "Kempsey",
    "Kiama Downs",
    "Kiama",
    "Kingscliff",
    "Korora",
    "Kurri Kurri",
    "Lake Cathie",
    "Lawson",
    "Leeton",
    "Lennox Head",
    "Leura",
    "Lismore",
    "Lithgow",
    "Macksville",
    "Maclean",
    "Maitland",
    "Manilla",
    "Merimbula",
    "Merrimac",
    "Mittagong",
    "Moama",
    "Molong",
    "Moree",
    "Morisset",
    "Moruya",
    "Moss Vale",
    "Mudgee",
    "Mullumbimby",
    "Murrumbateman",
    "Murwillumbah",
    "Muswellbrook",
    "Nambucca Heads",
    "Narooma",
    "Narrabri",
    "Narrandera",
    "Narromine",
    "Nelson Bay",
    "Newcastle",
    "Nowra",
    "Oberon",
    "Ocean Shores",
    "Old Bar",
    "Orange",
    "Parkes",
    "Penrith",
    "Picton",
    "Port Macquarie",
    "Pottsville",
    "Quakers Hill",
    "Queanbeyan",
    "Quirindi",
    "Raymond Terrace",
    "Richmond",
    "Rutherford",
    "Saint Georges Basin",
    "Salamander Bay",
    "Sanctuary Point",
    "Sawtell",
    "Scone",
    "Shoalhaven Heads",
    "Silverdale",
    "Singleton",
    "South Grafton",
    "South West Rocks",
    "Springwood",
    "Suffolk Park",
    "Sussex Inlet",
    "Sydney",
    "Tahmoor",
    "Tamworth",
    "Taree",
    "Tea Gardens",
    "Temora",
    "Tenterfield",
    "Terranora",
    "The Entrance",
    "The Oaks",
    "Thirlmere",
    "Tumut",
    "Tuncurry",
    "Tura Beach",
    "Tweed Heads",
    "Ulladulla",
    "Uralla",
    "Urunga",
    "Vincentia",
    "Wagga Wagga",
    "Walcha",
    "Wauchope",
    "Wellington",
    "Wentworth Falls",
    "West Wyalong",
    "Weston",
    "Wilberforce",
    "Wilton",
    "Wingham",
    "Wollongbar",
    "Wollongong",
    "Woolgoolga",
    "Worragee",
    "Wyong",
    "Yamba",
    "Yass",
    "Young"
  ],
  "vic": [
    "Alexandra",
    "Anglesea",
    "Ararat",
    "Bacchus Marsh",
    "Bairnsdale",
    "Ballan",
    "Ballarat",
    "Bannockburn",
    "Barwon Heads",
    "Beaconsfield Upper",
    "Beechworth",
    "Bellbrae",
    "Benalla",
    "Bendigo",
    "Broadford",
    "Buninyong",
    "Bunyip",
    "Camperdown",
    "Castlemaine",
    "Churchill",
    "Clifton Springs",
    "Cobram",
    "Cockatoo",
    "Cohuna",
    "Colac",
    "Cowes",
    "Cranbourne",
    "Creswick",
    "Crib Point",
    "Dandenong",
    "Darley",
    "Daylesford",
    "Dromana",
    "Drouin",
    "Drysdale",
    "Echuca",
    "Emerald",
    "Euroa",
    "Frankston",
    "Geelong",
    "Gisborne",
    "Hamilton",
    "Healesville",
    "Heathcote",
    "Horsham",
    "Hurstbridge",
    "Inverloch",
    "Irymple",
    "Junortoun",
    "Kangaroo Flat",
    "Kerang",
    "Kilmore",
    "Koo-Wee-Rup",
    "Korumburra",
    "Kyabram",
    "Kyneton",
    "Lakes Entrance",
    "Lancefield",
    "Lara",
    "Leongatha",
    "Leopold",
    "Lysterfield",
    "Maddingley",
    "Maffra",
    "Mansfield",
    "Maryborough",
    "McCrae",
    "Melbourne",
    "Melton",
    "Merbein",
    "Mildura",
    "Miners Rest",
    "Moe",
    "Mooroopna",
    "Morwell",
    "Mount Eliza",
    "Mount Evelyn",
    "Myrtleford",
    "Narre Warren North",
    "North Wonthaggi",
    "Numurkah",
    "Pakenham",
    "Paynesville",
    "Pearcedale",
    "Point Lonsdale",
    "Port Fairy",
    "Portarlington",
    "Portland",
    "Red Cliffs",
    "Riddell",
    "Robinvale",
    "Rochester",
    "Romsey",
    "Rye",
    "Saint Leonards",
    "Sale",
    "Seymour",
    "Shepparton",
    "Somerville",
    "Stawell",
    "Stratford",
    "Sunbury",
    "Swan Hill",
    "Tatura",
    "Torquay",
    "Trafalgar",
    "Traralgon",
    "Tyabb",
    "Wallan",
    "Wangaratta",
    "Warragul",
    "Warrnambool",
    "Whittlesea",
    "Wodonga",
    "Wollert",
    "Wonga Park",
    "Wonthaggi",
    "Woodend",
    "Woori Yallock",
    "Yarra Glen",
    "Yarra Junction",
    "Yarrawonga"
  ],
  "qld": [
    "Andergrove",
    "Atherton",
    "Ayr",
    "Bargara",
    "Beachmere",
    "Beaudesert",
    "Beerwah",
    "Biloela",
    "Blackwater",
    "Bli Bli",
    "Bohle Plains",
    "Bongaree",
    "Boonah",
    "Bowen",
    "Boyne Island",
    "Brisbane",
    "Bucasia",
    "Bundaberg",
    "Burnett Heads",
    "Burpengary",
    "Caboolture",
    "Cairns",
    "Calliope",
    "Caloundra",
    "Cannonvale",
    "Charleville",
    "Charters Towers",
    "Chinchilla",
    "Clermont",
    "Cloncurry",
    "Cooktown",
    "Cooloola Cove",
    "Cooroy",
    "Corinda",
    "Currumbin",
    "Dalby",
    "Dysart",
    "Emerald",
    "Fernvale",
    "Gatton",
    "Gladstone",
    "Glass House Mountains",
    "Glenella",
    "Gold Coast",
    "Goondiwindi",
    "Gordonvale",
    "Gracemere",
    "Gympie",
    "Hervey Bay",
    "Highfields",
    "Home Hill",
    "Ingham",
    "Innisfail",
    "Ipswich",
    "Jimboomba",
    "Karana Downs",
    "Kingaroy",
    "Kuranda",
    "Laidley",
    "Landsborough",
    "Logan Village",
    "Longreach",
    "Lowood",
    "Mackay",
    "Maleny",
    "Marcoola",
    "Mareeba",
    "Marian",
    "Maryborough",
    "Mooloolah",
    "Moore Park",
    "Moranbah",
    "Mount Cotton",
    "Mount Isa",
    "Mount Low",
    "Nambour",
    "Nanango",
    "Narangba",
    "Nerang",
    "Ningi",
    "North Mackay",
    "North Tamborine",
    "Oakey",
    "Palm Island",
    "Palmwoods",
    "Peregian Beach",
    "Pittsworth",
    "Point Vernon",
    "Pomona",
    "Port Douglas",
    "Proserpine",
    "Rasmussen",
    "Riverview",
    "Rochedale",
    "Rockhampton",
    "Roma",
    "Rosewood",
    "Saint George",
    "Samford",
    "Sandstone Point",
    "Sarina",
    "Scarness",
    "Smithfield Heights",
    "Southport",
    "Stanthorpe",
    "Tallebudgera",
    "Tambourine",
    "Tannum Sands",
    "Thursday Island",
    "Tolga",
    "Toowoomba",
    "Townsville",
    "Urraween",
    "Walkerston",
    "Warwick",
    "Waterford",
    "Weipa",
    "Westbrook",
    "Woodford",
    "Woombye",
    "Yarrabah Aboriginal Community",
    "Yeppoon"
  ],
  "wa": [
    "Albany",
    "Australind",
    "Bentley",
    "Boulder",
    "Bridgetown",
    "Broome",
    "Bullsbrook",
    "Bunbury",
    "Busselton",
    "Cannington",
    "Capel",
    "Carnarvon",
    "Collie",
    "Denmark",
    "Derby",
    "Donnybrook",
    "Dunsborough",
    "Esperance",
    "Exmouth",
    "Fremantle",
    "Geraldton",
    "Harvey",
    "Kalgoorlie",
    "Kambalda",
    "Karratha",
    "Katanning",
    "Kununurra",
    "Kwinana",
    "Leschenault",
    "Lesmurdie",
    "Mandurah",
    "Manjimup",
    "Margaret River",
    "Merredin",
    "Narrogin",
    "Newman",
    "North Beach",
    "Northam",
    "Perth",
    "Pinjarra",
    "Port Hedland",
    "Tom Price",
    "Two Rocks",
    "Vasse",
    "Waroona",
    "Wooroloo",
    "Yanchep",
    "York"
  ],
  "sa": [
    "Adelaide",
    "Aldgate",
    "Angle Vale",
    "Berri",
    "Bordertown",
    "Bridgewater",
    "Clare",
    "Encounter Bay",
    "Gawler",
    "Hahndorf",
    "Kadina",
    "Kapunda",
    "Lewiston",
    "Little Hampton",
    "Lobethal",
    "Loxton",
    "Mannum",
    "McLaren Vale",
    "Millicent",
    "Mount Barker",
    "Mount Gambier",
    "Murray Bridge",
    "Nairne",
    "Naracoorte",
    "Nuriootpa",
    "Port Augusta",
    "Port Lincoln",
    "Port Pirie",
    "Renmark",
    "Roxby Downs",
    "Stirling North",
    "Stirling",
    "Strathalbyn",
    "Tanunda",
    "Victor Harbor",
    "Waikerie",
    "Wallaroo",
    "Whyalla",
    "Williamstown",
    "Woodside"
  ],
  "act": [
    "Canberra"
  ],
  "tas": [
    "Burnie",
    "Currie",
    "Deloraine",
    "Devonport",
    "Dodges Ferry",
    "George Town",
    "Hobart",
    "Huonville",
    "Kingston",
    "Latrobe",
    "Launceston",
    "Legana",
    "Longford",
    "Margate",
    "New Norfolk",
    "Penguin",
    "Perth",
    "Smithton",
    "Somerset",
    "Sorell",
    "Ulverstone",
    "Wynyard"
  ],
  "nt": [
    "Alice Springs",
    "Darwin",
    "Howard Springs",
    "McMinns Lagoon",
    "Nhulunbuy"
  ]
};
